hostname: 10.18.10.111
port: 3306
dbName: guoyi_quantum
username: root
password: EybTcTBcJCdjwOFh

exportTableNames:
  - enterprise
  - sys_user
  - sys_role
  - sys_menu
  - sys_user_jupyter
  - sys_user_role
  - sys_role_menu
  - sys_minio_file
  - fund_account
  - fund_cost
  - daily_bill
  - monthly_bill
  - bill_transaction
  - task
  - simulator
  - simulator_instance
  - simulator_logical_gate
  - simulator_instance_logical_gate
